# Generated by Django 3.1.5 on 2021-01-27 23:11

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('img', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'project',
            },
        ),
    ]
