# Generated by Django 3.1.5 on 2021-01-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'projects', 'verbose_name_plural': 'project'},
        ),
    ]
