# Generated by Django 3.1.5 on 2021-01-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210127_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='resume',
            field=models.CharField(default='', max_length=256, verbose_name='resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
