# Generated by Django 3.1.5 on 2021-01-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210127_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.CharField(default='', max_length=256, verbose_name='github'),
            preserve_default=False,
        ),
    ]
