# Generated by Django 3.1.5 on 2021-01-28 20:26

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projects_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='github',
            field=models.CharField(blank=True, max_length=256, verbose_name='github'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=stdimage.models.StdImageField(blank=True, upload_to=core.models.get_file_path, verbose_name='Image'),
        ),
    ]
