# Generated by Django 3.1.5 on 2021-01-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projects_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='repository',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
