# Generated by Django 3.1.5 on 2021-01-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projects_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='categories',
            field=models.ManyToManyField(to='core.Categories'),
        ),
    ]
