# Generated by Django 3.1.5 on 2021-01-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210131_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'categorie', 'verbose_name_plural': 'categories'},
        ),
    ]
